server:
  port: 8081

spring:
  application:
    name: springboot-tools-demo
# h2数据库
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  #  自定义Banner
  banner:
    charset: UTF-8
    location: classpath:templates/banner.txt

logging:
  level:
    root: debug
  path: C:/data/logs/springboot-logback-demo

debug: false
